[package]
name = "bevy_core_widgets"
version = "0.1.0"
edition = "2021"

[dependencies]
accesskit = "0.18.0"
bevy = { version = "0.16.0-dev" }
# bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "refs/pull/18706/head" }
